// proto/request.proto

//
//the request body structured protobuf config for the forward request

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/forwardRequest.proto

package test

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestMethod int32

const (
	RequestMethod_GET    RequestMethod = 0
	RequestMethod_POST   RequestMethod = 1
	RequestMethod_PUT    RequestMethod = 2
	RequestMethod_PATCH  RequestMethod = 3
	RequestMethod_DELETE RequestMethod = 4
)

// Enum value maps for RequestMethod.
var (
	RequestMethod_name = map[int32]string{
		0: "GET",
		1: "POST",
		2: "PUT",
		3: "PATCH",
		4: "DELETE",
	}
	RequestMethod_value = map[string]int32{
		"GET":    0,
		"POST":   1,
		"PUT":    2,
		"PATCH":  3,
		"DELETE": 4,
	}
)

func (x RequestMethod) Enum() *RequestMethod {
	p := new(RequestMethod)
	*p = x
	return p
}

func (x RequestMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_forwardRequest_proto_enumTypes[0].Descriptor()
}

func (RequestMethod) Type() protoreflect.EnumType {
	return &file_proto_forwardRequest_proto_enumTypes[0]
}

func (x RequestMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestMethod.Descriptor instead.
func (RequestMethod) EnumDescriptor() ([]byte, []int) {
	return file_proto_forwardRequest_proto_rawDescGZIP(), []int{0}
}

type Headers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Headers) Reset() {
	*x = Headers{}
	mi := &file_proto_forwardRequest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Headers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Headers) ProtoMessage() {}

func (x *Headers) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forwardRequest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Headers.ProtoReflect.Descriptor instead.
func (*Headers) Descriptor() ([]byte, []int) {
	return file_proto_forwardRequest_proto_rawDescGZIP(), []int{0}
}

func (x *Headers) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Headers) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Method        RequestMethod          `protobuf:"varint,2,opt,name=method,proto3,enum=forwardRequest.RequestMethod" json:"method,omitempty"`
	Headers       []*Headers             `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty"`
	Body          []byte                 `protobuf:"bytes,4,opt,name=body,proto3,oneof" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_proto_forwardRequest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forwardRequest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_proto_forwardRequest_proto_rawDescGZIP(), []int{1}
}

func (x *Request) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Request) GetMethod() RequestMethod {
	if x != nil {
		return x.Method
	}
	return RequestMethod_GET
}

func (x *Request) GetHeaders() []*Headers {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Request) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_proto_forwardRequest_proto protoreflect.FileDescriptor

const file_proto_forwardRequest_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/forwardRequest.proto\x12\x0eforwardRequest\"1\n" +
	"\aHeaders\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xa7\x01\n" +
	"\aRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x125\n" +
	"\x06method\x18\x02 \x01(\x0e2\x1d.forwardRequest.RequestMethodR\x06method\x121\n" +
	"\aheaders\x18\x03 \x03(\v2\x17.forwardRequest.HeadersR\aheaders\x12\x17\n" +
	"\x04body\x18\x04 \x01(\fH\x00R\x04body\x88\x01\x01B\a\n" +
	"\x05_body*B\n" +
	"\rRequestMethod\x12\a\n" +
	"\x03GET\x10\x00\x12\b\n" +
	"\x04POST\x10\x01\x12\a\n" +
	"\x03PUT\x10\x02\x12\t\n" +
	"\x05PATCH\x10\x03\x12\n" +
	"\n" +
	"\x06DELETE\x10\x04B'Z%github.com/prdai/cf-region-proxy/testb\x06proto3"

var (
	file_proto_forwardRequest_proto_rawDescOnce sync.Once
	file_proto_forwardRequest_proto_rawDescData []byte
)

func file_proto_forwardRequest_proto_rawDescGZIP() []byte {
	file_proto_forwardRequest_proto_rawDescOnce.Do(func() {
		file_proto_forwardRequest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_forwardRequest_proto_rawDesc), len(file_proto_forwardRequest_proto_rawDesc)))
	})
	return file_proto_forwardRequest_proto_rawDescData
}

var file_proto_forwardRequest_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_forwardRequest_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_forwardRequest_proto_goTypes = []any{
	(RequestMethod)(0), // 0: forwardRequest.RequestMethod
	(*Headers)(nil),    // 1: forwardRequest.Headers
	(*Request)(nil),    // 2: forwardRequest.Request
}
var file_proto_forwardRequest_proto_depIdxs = []int32{
	0, // 0: forwardRequest.Request.method:type_name -> forwardRequest.RequestMethod
	1, // 1: forwardRequest.Request.headers:type_name -> forwardRequest.Headers
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_forwardRequest_proto_init() }
func file_proto_forwardRequest_proto_init() {
	if File_proto_forwardRequest_proto != nil {
		return
	}
	file_proto_forwardRequest_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_forwardRequest_proto_rawDesc), len(file_proto_forwardRequest_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_forwardRequest_proto_goTypes,
		DependencyIndexes: file_proto_forwardRequest_proto_depIdxs,
		EnumInfos:         file_proto_forwardRequest_proto_enumTypes,
		MessageInfos:      file_proto_forwardRequest_proto_msgTypes,
	}.Build()
	File_proto_forwardRequest_proto = out.File
	file_proto_forwardRequest_proto_goTypes = nil
	file_proto_forwardRequest_proto_depIdxs = nil
}
