/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 7.34.1
 * source: proto/_headers.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export class Headers extends pb_1.Message {
	#one_of_decls: number[][] = [];
	constructor(
		data?:
			| any[]
			| {
					key?: string;
					value?: string;
			  },
	) {
		super();
		pb_1.Message.initialize(
			this,
			Array.isArray(data) ? data : [],
			0,
			-1,
			[],
			this.#one_of_decls,
		);
		if (!Array.isArray(data) && typeof data == "object") {
			if ("key" in data && data.key != undefined) {
				this.key = data.key;
			}
			if ("value" in data && data.value != undefined) {
				this.value = data.value;
			}
		}
	}
	get key() {
		return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
	}
	set key(value: string) {
		pb_1.Message.setField(this, 1, value);
	}
	get value() {
		return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
	}
	set value(value: string) {
		pb_1.Message.setField(this, 2, value);
	}
	static fromObject(data: { key?: string; value?: string }): Headers {
		const message = new Headers({});
		if (data.key != null) {
			message.key = data.key;
		}
		if (data.value != null) {
			message.value = data.value;
		}
		return message;
	}
	toObject() {
		const data: {
			key?: string;
			value?: string;
		} = {};
		if (this.key != null) {
			data.key = this.key;
		}
		if (this.value != null) {
			data.value = this.value;
		}
		return data;
	}
	serialize(): Uint8Array;
	serialize(w: pb_1.BinaryWriter): void;
	serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
		const writer = w || new pb_1.BinaryWriter();
		if (this.key.length) writer.writeString(1, this.key);
		if (this.value.length) writer.writeString(2, this.value);
		if (!w) return writer.getResultBuffer();
	}
	static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Headers {
		const reader =
				bytes instanceof pb_1.BinaryReader
					? bytes
					: new pb_1.BinaryReader(bytes),
			message = new Headers();
		while (reader.nextField()) {
			if (reader.isEndGroup()) break;
			switch (reader.getFieldNumber()) {
				case 1:
					message.key = reader.readString();
					break;
				case 2:
					message.value = reader.readString();
					break;
				default:
					reader.skipField();
			}
		}
		return message;
	}
	serializeBinary(): Uint8Array {
		return this.serialize();
	}
	static deserializeBinary(bytes: Uint8Array): Headers {
		return Headers.deserialize(bytes);
	}
}
