/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 7.34.1
 * source: proto/_method.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export enum RequestMethod {
	GET = 0,
	POST = 1,
	PUT = 2,
	PATCH = 3,
	DELETE = 4,
}
