/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 7.34.1
 * source: proto/forwardRequest.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./_method";
import * as dependency_2 from "./_headers";
import * as pb_1 from "google-protobuf";
export namespace forwardRequest {
	export class Request extends pb_1.Message {
		#one_of_decls: number[][] = [[4]];
		constructor(
			data?:
				| any[]
				| ({
						url?: string;
						method?: dependency_1.RequestMethod;
						headers?: dependency_2.Headers[];
				  } & {
						body?: Uint8Array;
				  }),
		) {
			super();
			pb_1.Message.initialize(
				this,
				Array.isArray(data) ? data : [],
				0,
				-1,
				[3],
				this.#one_of_decls,
			);
			if (!Array.isArray(data) && typeof data == "object") {
				if ("url" in data && data.url != undefined) {
					this.url = data.url;
				}
				if ("method" in data && data.method != undefined) {
					this.method = data.method;
				}
				if ("headers" in data && data.headers != undefined) {
					this.headers = data.headers;
				}
				if ("body" in data && data.body != undefined) {
					this.body = data.body;
				}
			}
		}
		get url() {
			return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
		}
		set url(value: string) {
			pb_1.Message.setField(this, 1, value);
		}
		get method() {
			return pb_1.Message.getFieldWithDefault(
				this,
				2,
				dependency_1.RequestMethod.GET,
			) as dependency_1.RequestMethod;
		}
		set method(value: dependency_1.RequestMethod) {
			pb_1.Message.setField(this, 2, value);
		}
		get headers() {
			return pb_1.Message.getRepeatedWrapperField(
				this,
				dependency_2.Headers,
				3,
			) as dependency_2.Headers[];
		}
		set headers(value: dependency_2.Headers[]) {
			pb_1.Message.setRepeatedWrapperField(this, 3, value);
		}
		get body() {
			return pb_1.Message.getFieldWithDefault(
				this,
				4,
				new Uint8Array(0),
			) as Uint8Array;
		}
		set body(value: Uint8Array) {
			pb_1.Message.setOneofField(this, 4, this.#one_of_decls[0], value);
		}
		get has_body() {
			return pb_1.Message.getField(this, 4) != null;
		}
		get _body() {
			const cases: {
				[index: number]: "none" | "body";
			} = {
				0: "none",
				4: "body",
			};
			return cases[pb_1.Message.computeOneofCase(this, [4])];
		}
		static fromObject(data: {
			url?: string;
			method?: dependency_1.RequestMethod;
			headers?: ReturnType<typeof dependency_2.Headers.prototype.toObject>[];
			body?: Uint8Array;
		}): Request {
			const message = new Request({});
			if (data.url != null) {
				message.url = data.url;
			}
			if (data.method != null) {
				message.method = data.method;
			}
			if (data.headers != null) {
				message.headers = data.headers.map((item) =>
					dependency_2.Headers.fromObject(item),
				);
			}
			if (data.body != null) {
				message.body = data.body;
			}
			return message;
		}
		toObject() {
			const data: {
				url?: string;
				method?: dependency_1.RequestMethod;
				headers?: ReturnType<typeof dependency_2.Headers.prototype.toObject>[];
				body?: Uint8Array;
			} = {};
			if (this.url != null) {
				data.url = this.url;
			}
			if (this.method != null) {
				data.method = this.method;
			}
			if (this.headers != null) {
				data.headers = this.headers.map((item: dependency_2.Headers) =>
					item.toObject(),
				);
			}
			if (this.body != null) {
				data.body = this.body;
			}
			return data;
		}
		serialize(): Uint8Array;
		serialize(w: pb_1.BinaryWriter): void;
		serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
			const writer = w || new pb_1.BinaryWriter();
			if (this.url.length) writer.writeString(1, this.url);
			if (this.method != dependency_1.RequestMethod.GET)
				writer.writeEnum(2, this.method);
			if (this.headers.length)
				writer.writeRepeatedMessage(
					3,
					this.headers,
					(item: dependency_2.Headers) => item.serialize(writer),
				);
			if (this.has_body) writer.writeBytes(4, this.body);
			if (!w) return writer.getResultBuffer();
		}
		static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Request {
			const reader =
					bytes instanceof pb_1.BinaryReader
						? bytes
						: new pb_1.BinaryReader(bytes),
				message = new Request();
			while (reader.nextField()) {
				if (reader.isEndGroup()) break;
				switch (reader.getFieldNumber()) {
					case 1:
						message.url = reader.readString();
						break;
					case 2:
						message.method = reader.readEnum();
						break;
					case 3:
						reader.readMessage(message.headers, () =>
							pb_1.Message.addToRepeatedWrapperField(
								message,
								3,
								dependency_2.Headers.deserialize(reader),
								dependency_2.Headers,
							),
						);
						break;
					case 4:
						message.body = reader.readBytes();
						break;
					default:
						reader.skipField();
				}
			}
			return message;
		}
		serializeBinary(): Uint8Array {
			return this.serialize();
		}
		static deserializeBinary(bytes: Uint8Array): Request {
			return Request.deserialize(bytes);
		}
	}
}
