/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 7.34.1
 * source: proto/request.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
export namespace request {
    export enum RequestMethod {
        GET = 0,
        POST = 1,
        PUT = 2
    }
    export class Request extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            method?: RequestMethod;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("method" in data && data.method != undefined) {
                    this.method = data.method;
                }
            }
        }
        get method() {
            return pb_1.Message.getFieldWithDefault(this, 1, RequestMethod.GET) as RequestMethod;
        }
        set method(value: RequestMethod) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data: {
            method?: RequestMethod;
        }): Request {
            const message = new Request({});
            if (data.method != null) {
                message.method = data.method;
            }
            return message;
        }
        toObject() {
            const data: {
                method?: RequestMethod;
            } = {};
            if (this.method != null) {
                data.method = this.method;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.method != RequestMethod.GET)
                writer.writeEnum(1, this.method);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Request {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Request();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.method = reader.readEnum();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): Request {
            return Request.deserialize(bytes);
        }
    }
}
